### ISSUE TITLE
Delete existing Experience

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/orientation-project-python-23.FAL#5]
Using a `DELETE` request for the `/resume/experience` route, delete an existing Experience using its index position as an ID. As part of this, you should write a test in `test_pytest.py` to show it works.

**Comment by Daquiver1** [comment]
Regarding this issue, I have written the test script. However, I am currently unable to execute the test due to the absence of the POST endpoint. @asuzukosi  is currently working on the implementation of the POST endpoint. So, I will only be able to run the test script once the endpoint is completed.
